"""initial schema

Revision ID: 92986dc11c3b
Revises: 
Create Date: 2026-10-02 15:27:31.070559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92986dc11c3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('portfolio', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('email', name=op.f('uq_candidates_email'))
    )
    op.create_table('company',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('company_name', name=op.f('uq_company_company_name'))
    )
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_table('cv',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('is_text_extracted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsing_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_cv_candidate_id_candidates'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cv'))
    )
    op.create_table('hr_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_hr_users_company_id_company'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_users')),
    sa.UniqueConstraint('email', name=op.f('uq_hr_users_email'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hr_id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colleges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_years_experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_jobs_company_id_company'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_users.id'], name=op.f('fk_jobs_hr_id_hr_users'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_status_end_date', 'jobs', ['status', 'end_date'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('cv_id', sa.BigInteger(), nullable=False),
    sa.Column('extracted_college', sa.String(length=100), nullable=True),
    sa.Column('extracted_years_experience', sa.Integer(), nullable=True),
    sa.Column('critical_rule_passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('match_explanation', sa.Text(), nullable=True),
    sa.Column('ats_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('hr_decision', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('rejection_cause', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], name=op.f('fk_applications_cv_id_cv'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['hr_users.id'], name=op.f('fk_applications_reviewed_by_hr_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_applications_candidate_id_job_id')
    )
    op.create_index('ix_applications_ats_status', 'applications', ['ats_status'], unique=False)
    op.create_index('ix_applications_hr_decision', 'applications', ['hr_decision'], unique=False)
    op.create_index('ix_applications_job_id_score', 'applications', ['job_id', 'score'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_skills_job_id_jobs'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_job_skills_skill_id_skills'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_skills')),
    sa.UniqueConstraint('job_id', 'skill_id', name='uq_job_skills_job_id_skill_id')
    )
    op.create_index('ix_job_skills_job_id_requirement_type', 'job_skills', ['job_id', 'requirement_type'], unique=False)
    op.create_index('ix_job_skills_skill_id', 'job_skills', ['skill_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_status_history_application_id_applications'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['hr_users.id'], name=op.f('fk_application_status_history_changed_by_hr_users'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_status_history')
    op.drop_index('ix_job_skills_skill_id', table_name='job_skills')
    op.drop_index('ix_job_skills_job_id_requirement_type', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('ix_applications_job_id_score', table_name='applications')
    op.drop_index('ix_applications_hr_decision', table_name='applications')
    op.drop_index('ix_applications_ats_status', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status_end_date', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('hr_users')
    op.drop_table('cv')
    op.drop_table('skills')
    op.drop_table('company')
    op.drop_table('candidates')
    # ### end Alembic commands ###
